{% set name = "pyscf_auto" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 31
  noarch: python

requirements:
  host:
    - python =3.12
    - pip
    - setuptools
  run:
    - __unix
    - python >=3.12,<3.13
    - ase
    - dftd3-python
    - dftd4-python
    - h5py
    - basis-set-exchange
    - numpy
    - pydantic >=2.0
    - pyscf * smd_py*
    - pyyaml >=6.0
    - sella
    - scipy

test:
  imports:
    - basis_set_exchange
    - sella
    - pyscf
    - pyscf.solvent.smd
  commands:
    - pyscf_auto --help

about:
  home: https://github.com/dhsohn/pyscf_auto
  summary: pyscf_auto CLI for PySCF/ASE workflows with SMD-enabled PySCF.
  license: MIT

extra:
  recipe-maintainers:
    - daehyupsohn
