name: Bug report
description: Report a reproducible bug in pyscf_auto
labels: ["type:bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the behavior and why it is a problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Commands, inputs, configs, minimal example.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs / traceback
      description: Paste relevant logs (redact paths if needed).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: OS, Python, conda env, pyscf/ase/dftd3 versions.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: false
