name: Feature request
description: Suggest an enhancement for pyscf_auto
labels: ["type:feature"]
body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: What would you like pyscf_auto to do?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance criteria
      description: How do we know it is done?
    validations:
      required: true
