{% set name = "basis-set-exchange" %}
{% set version = "0.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/b/basis-set-exchange/basis_set_exchange-{{ version }}.tar.gz
  sha256: 80f89348e4cc52b12f89391f923564eb5f877e316e2f8fe1e4f28df769d2c852

build:
  number: 1
  noarch: python

requirements:
  host:
    - python =3.12
    - pip
    - setuptools
  run:
    - python >=3.12,<3.13
    - jsonschema
    - argcomplete
    - regex
    - unidecode

test:
  imports:
    - basis_set_exchange

about:
  home: https://github.com/MolSSI-BSE/basis_set_exchange
  summary: Basis Set Exchange library and CLI.
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - daehyupsohn
